nla:
  name: 'National Library of Australia'
  description: 'Replace me with a more descriptive description for this repository.'
  building: 'National Library of Australia'
  address1: 'Parkes Pl W'
  address2: ''
  city: 'Canberra'
  state: 'ACT'
  zip: '2600'
  country: 'AUS'
  phone: '+61 (0)2 6262 1111'
  contact_info: ''
  thumbnail_url: "https://www.nla.gov.au/themes/custom/nlaweb/logo.svg?a"
  request_types:
    google_form:
      request_url: 'https://docs.google.com/a/stanford.edu/forms/d/e/1FAIpQLSeOamhY_IcFw4sPnz0ddwWWkrPaHbM5wp7JVbOLOL_mIusEyw/viewform'
      request_mappings: "document_url=entry.1980510262&collection_name=entry.619150170&collection_creator=entry.14428541&eadid=entry.996397105&containers=entry.1125277048&title=entry.862815208"
