nla:
  name: 'National Library of Australia'
  visit_note: ''
  description: 'Replace me with a more descriptive description for this repository.'
  building: 'National Library of Australia'
  address1: 'Parkes Pl W'
  address2: ''
  city: 'Canberra'
  state: 'ACT'
  zip: '2600'
  country: 'AUS'
  phone: '+61 (0)2 6262 1111'
  contact_info: ''
  thumbnail_url: "https://assets.nla.gov.au/logos/nla/nla.svg"
