version: '3'
services:
  solr:
    image: solr:8.7.0
    environment:
      SOLR_HEAP: 4g
    ports:
      - "8983:8983"
    volumes:
      - .:/arclight_config
    command: solr-precreate arclight /arclight_config
